#### Main UI
'''
    Copyright (C) 2020 Oliver Rodriguez
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
'''
#### @author oliverrdz
#### https://oliverrdz.xyz


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(721, 523)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 341, 411))
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 30, 321, 371))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setContentsMargins(0, 0, 0, 0)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.box_n = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.box_n.setObjectName("box_n")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.box_n)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.box_A = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.box_A.setEnabled(True)
        self.box_A.setObjectName("box_A")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.box_A)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.box_E0 = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.box_E0.setObjectName("box_E0")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.box_E0)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.box_COb = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.box_COb.setEnabled(False)
        self.box_COb.setObjectName("box_COb")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.box_COb)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.box_DO = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.box_DO.setObjectName("box_DO")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.box_DO)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.box_DR = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.box_DR.setObjectName("box_DR")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.box_DR)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.box_ks = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.box_ks.setEnabled(False)
        self.box_ks.setObjectName("box_ks")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.box_ks)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_14.setObjectName("label_14")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.box_alpha = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.box_alpha.setEnabled(False)
        self.box_alpha.setObjectName("box_alpha")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.box_alpha)
        self.label_15 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_15)
        self.box_Cd = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.box_Cd.setEnabled(False)
        self.box_Cd.setObjectName("box_Cd")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.box_Cd)
        self.label_16 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_16.setObjectName("label_16")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.box_Ru = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.box_Ru.setEnabled(False)
        self.box_Ru.setObjectName("box_Ru")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.box_Ru)
        self.label_12 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.box_CRb = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        self.box_CRb.setObjectName("box_CRb")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.box_CRb)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(370, 10, 341, 51))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 311, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radBtn_Nernst = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radBtn_Nernst.setChecked(True)
        self.radBtn_Nernst.setObjectName("radBtn_Nernst")
        self.horizontalLayout_2.addWidget(self.radBtn_Nernst)
        self.radBtn_BV = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radBtn_BV.setObjectName("radBtn_BV")
        self.horizontalLayout_2.addWidget(self.radBtn_BV)
        self.radBtn_Irrev = QtWidgets.QRadioButton(self.horizontalLayoutWidget_2)
        self.radBtn_Irrev.setObjectName("radBtn_Irrev")
        self.horizontalLayout_2.addWidget(self.radBtn_Irrev)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(370, 430, 331, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnSimulate = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnSimulate.setEnabled(False)
        self.btnSimulate.setObjectName("btnSimulate")
        self.horizontalLayout.addWidget(self.btnSimulate)
        self.btnPlot = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnPlot.setEnabled(False)
        self.btnPlot.setObjectName("btnPlot")
        self.horizontalLayout.addWidget(self.btnPlot)
        self.btnAnimate = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnAnimate.setEnabled(False)
        self.btnAnimate.setObjectName("btnAnimate")
        self.horizontalLayout.addWidget(self.btnAnimate)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(20, 430, 331, 41))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.progressBar = QtWidgets.QProgressBar(self.verticalLayoutWidget_3)
        self.progressBar.setEnabled(False)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_3.addWidget(self.progressBar)
        self.layout_Waveform = QtWidgets.QTabWidget(self.centralwidget)
        self.layout_Waveform.setGeometry(QtCore.QRect(370, 70, 331, 341))
        self.layout_Waveform.setObjectName("layout_Waveform")
        self.tab_CV = QtWidgets.QWidget()
        self.tab_CV.setObjectName("tab_CV")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab_CV)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 301, 171))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setEnabled(True)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.box_Eini = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.box_Eini.setReadOnly(False)
        self.box_Eini.setObjectName("box_Eini")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.box_Eini)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.box_Efin = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.box_Efin.setObjectName("box_Efin")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.box_Efin)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.box_sr = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.box_sr.setObjectName("box_sr")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.box_sr)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.box_dE = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.box_dE.setObjectName("box_dE")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.box_dE)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.box_ns = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.box_ns.setObjectName("box_ns")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.box_ns)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.tab_CV)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 270, 301, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_genSweep = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.btn_genSweep.setObjectName("btn_genSweep")
        self.horizontalLayout_3.addWidget(self.btn_genSweep)
        self.btn_plotSweep = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.btn_plotSweep.setEnabled(False)
        self.btn_plotSweep.setObjectName("btn_plotSweep")
        self.horizontalLayout_3.addWidget(self.btn_plotSweep)
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.tab_CV)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(9, 190, 301, 71))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.check_Mult_sr = QtWidgets.QCheckBox(self.horizontalLayoutWidget_6)
        self.check_Mult_sr.setObjectName("check_Mult_sr")
        self.horizontalLayout_6.addWidget(self.check_Mult_sr)
        self.box_Mult_sr = QtWidgets.QPlainTextEdit(self.horizontalLayoutWidget_6)
        self.box_Mult_sr.setEnabled(False)
        self.box_Mult_sr.setObjectName("box_Mult_sr")
        self.horizontalLayout_6.addWidget(self.box_Mult_sr)
        self.layout_Waveform.addTab(self.tab_CV, "")
        self.tab_CA = QtWidgets.QWidget()
        self.tab_CA.setObjectName("tab_CA")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.tab_CA)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(10, 10, 301, 231))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setContentsMargins(0, 0, 0, 0)
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_17.setObjectName("label_17")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_17)
        self.box_Estep = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.box_Estep.setObjectName("box_Estep")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.box_Estep)
        self.label_18 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_18.setObjectName("label_18")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_18)
        self.box_ttot = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.box_ttot.setObjectName("box_ttot")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.box_ttot)
        self.label_19 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_19.setObjectName("label_19")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_19)
        self.box_dt = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.box_dt.setObjectName("box_dt")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.box_dt)
        self.check_SecondStep = QtWidgets.QCheckBox(self.formLayoutWidget_4)
        self.check_SecondStep.setObjectName("check_SecondStep")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.check_SecondStep)
        self.label_20 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_20.setObjectName("label_20")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_20)
        self.box_Estep2 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.box_Estep2.setEnabled(False)
        self.box_Estep2.setObjectName("box_Estep2")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.box_Estep2)
        self.label_21 = QtWidgets.QLabel(self.formLayoutWidget_4)
        self.label_21.setObjectName("label_21")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_21)
        self.box_ttot2 = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        self.box_ttot2.setEnabled(False)
        self.box_ttot2.setObjectName("box_ttot2")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.box_ttot2)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.tab_CA)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(10, 270, 301, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_genStep = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.btn_genStep.setObjectName("btn_genStep")
        self.horizontalLayout_4.addWidget(self.btn_genStep)
        self.btn_plotStep = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.btn_plotStep.setEnabled(False)
        self.btn_plotStep.setObjectName("btn_plotStep")
        self.horizontalLayout_4.addWidget(self.btn_plotStep)
        self.layout_Waveform.addTab(self.tab_CA, "")
        self.tab_SCV = QtWidgets.QWidget()
        self.tab_SCV.setObjectName("tab_SCV")
        self.formLayoutWidget_5 = QtWidgets.QWidget(self.tab_SCV)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(10, 10, 301, 181))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.formLayout_5 = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.formLayout_5.setContentsMargins(0, 0, 0, 0)
        self.formLayout_5.setObjectName("formLayout_5")
        self.label_22 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_22.setObjectName("label_22")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_22)
        self.box_Eini_SCV = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.box_Eini_SCV.setObjectName("box_Eini_SCV")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.box_Eini_SCV)
        self.label_23 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_23.setObjectName("label_23")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_23)
        self.box_Efin_SCV = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.box_Efin_SCV.setObjectName("box_Efin_SCV")
        self.formLayout_5.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.box_Efin_SCV)
        self.label_24 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_24.setObjectName("label_24")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_24)
        self.box_dE_SCV = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.box_dE_SCV.setObjectName("box_dE_SCV")
        self.formLayout_5.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.box_dE_SCV)
        self.label_25 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_25.setObjectName("label_25")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_25)
        self.label_26 = QtWidgets.QLabel(self.formLayoutWidget_5)
        self.label_26.setObjectName("label_26")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_26)
        self.box_dt_SCV = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.box_dt_SCV.setObjectName("box_dt_SCV")
        self.formLayout_5.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.box_dt_SCV)
        self.box_ttot_SCV = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        self.box_ttot_SCV.setObjectName("box_ttot_SCV")
        self.formLayout_5.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.box_ttot_SCV)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.tab_SCV)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(10, 270, 301, 31))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btn_genSCV = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.btn_genSCV.setObjectName("btn_genSCV")
        self.horizontalLayout_5.addWidget(self.btn_genSCV)
        self.btn_plotSCV = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.btn_plotSCV.setEnabled(False)
        self.btn_plotSCV.setObjectName("btn_plotSCV")
        self.horizontalLayout_5.addWidget(self.btn_plotSCV)
        self.layout_Waveform.addTab(self.tab_SCV, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 721, 25))
        self.menubar.setObjectName("menubar")
        self.menuNew = QtWidgets.QMenu(self.menubar)
        self.menuNew.setObjectName("menuNew")
        self.menuSave = QtWidgets.QMenu(self.menuNew)
        self.menuSave.setObjectName("menuSave")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionCV = QtWidgets.QAction(MainWindow)
        self.actionCV.setObjectName("actionCV")
        self.actionChronoamperometry = QtWidgets.QAction(MainWindow)
        self.actionChronoamperometry.setEnabled(False)
        self.actionChronoamperometry.setObjectName("actionChronoamperometry")
        self.actionSampled_current_voltammetry = QtWidgets.QAction(MainWindow)
        self.actionSampled_current_voltammetry.setEnabled(False)
        self.actionSampled_current_voltammetry.setObjectName("actionSampled_current_voltammetry")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSave_figures = QtWidgets.QAction(MainWindow)
        self.actionSave_figures.setEnabled(False)
        self.actionSave_figures.setObjectName("actionSave_figures")
        self.actionSave_data = QtWidgets.QAction(MainWindow)
        self.actionSave_data.setEnabled(False)
        self.actionSave_data.setObjectName("actionSave_data")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionWiki = QtWidgets.QAction(MainWindow)
        self.actionWiki.setObjectName("actionWiki")
        self.actionEFD = QtWidgets.QAction(MainWindow)
        self.actionEFD.setObjectName("actionEFD")
        self.actionBI = QtWidgets.QAction(MainWindow)
        self.actionBI.setEnabled(False)
        self.actionBI.setObjectName("actionBI")
        self.actionSave_Waveform = QtWidgets.QAction(MainWindow)
        self.actionSave_Waveform.setEnabled(False)
        self.actionSave_Waveform.setObjectName("actionSave_Waveform")
        self.actionSave_Current = QtWidgets.QAction(MainWindow)
        self.actionSave_Current.setEnabled(False)
        self.actionSave_Current.setObjectName("actionSave_Current")
        self.actionSave_O = QtWidgets.QAction(MainWindow)
        self.actionSave_O.setEnabled(False)
        self.actionSave_O.setObjectName("actionSave_O")
        self.actionSave_R = QtWidgets.QAction(MainWindow)
        self.actionSave_R.setEnabled(False)
        self.actionSave_R.setObjectName("actionSave_R")
        self.actionSave_x = QtWidgets.QAction(MainWindow)
        self.actionSave_x.setEnabled(False)
        self.actionSave_x.setObjectName("actionSave_x")
        self.menuSave.addAction(self.actionSave_Current)
        self.menuSave.addAction(self.actionSave_Waveform)
        self.menuSave.addAction(self.actionSave_O)
        self.menuSave.addAction(self.actionSave_R)
        self.menuSave.addAction(self.actionSave_x)
        self.menuNew.addSeparator()
        self.menuNew.addAction(self.menuSave.menuAction())
        self.menuNew.addAction(self.actionExit)
        self.menuNew.addSeparator()
        self.menuHelp.addAction(self.actionWiki)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuNew.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.layout_Waveform.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Soft Potato"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Electrochemistry parameters:"))
        self.label_6.setText(_translate("MainWindow", "Number of electrons:"))
        self.box_n.setText(_translate("MainWindow", "1"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p>Geometrical area (cm<span style=\" vertical-align:super;\">2</span>):</p></body></html>"))
        self.box_A.setText(_translate("MainWindow", "1"))
        self.label_8.setText(_translate("MainWindow", "Standard potential (V):"))
        self.box_E0.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p>Bulk concentration of O (mol/cm<span style=\" vertical-align:super;\">3</span>):</p></body></html>"))
        self.box_COb.setText(_translate("MainWindow", "0"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p>Diffusion coefficient of O (cm<span style=\" vertical-align:super;\">2</span>/s):</p></body></html>"))
        self.box_DO.setText(_translate("MainWindow", "1e-5"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p>Diffusion coefficient of R (cm<span style=\" vertical-align:super;\">2</span>/s):</p></body></html>"))
        self.box_DR.setText(_translate("MainWindow", "1e-5"))
        self.label_13.setText(_translate("MainWindow", "Standard rate constant (cm/s):"))
        self.box_ks.setText(_translate("MainWindow", "1e-3"))
        self.label_14.setText(_translate("MainWindow", "Transfer coefficient:"))
        self.box_alpha.setText(_translate("MainWindow", "0.5"))
        self.label_15.setText(_translate("MainWindow", "Double layer capacitance (F):"))
        self.box_Cd.setText(_translate("MainWindow", "0"))
        self.label_16.setText(_translate("MainWindow", "Solution resistance (ohms):"))
        self.box_Ru.setText(_translate("MainWindow", "0"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p>Bulk concentration of R (mol/cm<span style=\" vertical-align:super;\">3</span>):</p></body></html>"))
        self.box_CRb.setText(_translate("MainWindow", "5e-6"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Surface concentration:"))
        self.radBtn_Nernst.setText(_translate("MainWindow", "Nernst"))
        self.radBtn_BV.setText(_translate("MainWindow", "Butler-Volmer"))
        self.radBtn_Irrev.setText(_translate("MainWindow", "BV irreversible"))
        self.btnSimulate.setText(_translate("MainWindow", "Simulate"))
        self.btnPlot.setText(_translate("MainWindow", "Plot"))
        self.btnAnimate.setText(_translate("MainWindow", "Animate"))
        self.label.setText(_translate("MainWindow", "Initial potential (V):"))
        self.box_Eini.setText(_translate("MainWindow", "-0.5"))
        self.label_2.setText(_translate("MainWindow", "Final potential (V):"))
        self.box_Efin.setText(_translate("MainWindow", "0.5"))
        self.label_3.setText(_translate("MainWindow", "Scan rate (V/s):"))
        self.box_sr.setText(_translate("MainWindow", "1"))
        self.label_4.setText(_translate("MainWindow", "Potential increment (V):"))
        self.box_dE.setText(_translate("MainWindow", "0.01"))
        self.label_5.setText(_translate("MainWindow", "Number of sweeps:"))
        self.box_ns.setText(_translate("MainWindow", "2"))
        self.btn_genSweep.setText(_translate("MainWindow", "Generate"))
        self.btn_plotSweep.setText(_translate("MainWindow", "Plot"))
        self.check_Mult_sr.setText(_translate("MainWindow", "Multiple scan rates"))
        self.box_Mult_sr.setPlainText(_translate("MainWindow", "1\n"
"10\n"
"100"))
        self.layout_Waveform.setTabText(self.layout_Waveform.indexOf(self.tab_CV), _translate("MainWindow", "CV"))
        self.label_17.setText(_translate("MainWindow", "Potential step (V):"))
        self.box_Estep.setText(_translate("MainWindow", "1"))
        self.label_18.setText(_translate("MainWindow", "Time for the step (s):"))
        self.box_ttot.setText(_translate("MainWindow", "1"))
        self.label_19.setText(_translate("MainWindow", "Time increment (s):"))
        self.box_dt.setText(_translate("MainWindow", "0.01"))
        self.check_SecondStep.setText(_translate("MainWindow", "Second step"))
        self.label_20.setText(_translate("MainWindow", "Potential step (V):"))
        self.box_Estep2.setText(_translate("MainWindow", "-1"))
        self.label_21.setText(_translate("MainWindow", "Time for the step (s):"))
        self.box_ttot2.setText(_translate("MainWindow", "1"))
        self.btn_genStep.setText(_translate("MainWindow", "Generate"))
        self.btn_plotStep.setText(_translate("MainWindow", "Plot"))
        self.layout_Waveform.setTabText(self.layout_Waveform.indexOf(self.tab_CA), _translate("MainWindow", "CA"))
        self.label_22.setText(_translate("MainWindow", "Initial potential (V):"))
        self.box_Eini_SCV.setText(_translate("MainWindow", "-0.5"))
        self.label_23.setText(_translate("MainWindow", "Final potential (V):"))
        self.box_Efin_SCV.setText(_translate("MainWindow", "0.5"))
        self.label_24.setText(_translate("MainWindow", "Potential increment (V):"))
        self.box_dE_SCV.setText(_translate("MainWindow", "0.01"))
        self.label_25.setText(_translate("MainWindow", "Time for each step (s):"))
        self.label_26.setText(_translate("MainWindow", "Time increment (s):"))
        self.box_dt_SCV.setText(_translate("MainWindow", "0.01"))
        self.box_ttot_SCV.setText(_translate("MainWindow", "1"))
        self.btn_genSCV.setText(_translate("MainWindow", "Generate"))
        self.btn_plotSCV.setText(_translate("MainWindow", "Plot"))
        self.layout_Waveform.setTabText(self.layout_Waveform.indexOf(self.tab_SCV), _translate("MainWindow", "SCV"))
        self.menuNew.setTitle(_translate("MainWindow", "File"))
        self.menuSave.setTitle(_translate("MainWindow", "Save"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionCV.setText(_translate("MainWindow", "Cyclic Voltammetry"))
        self.actionChronoamperometry.setText(_translate("MainWindow", "Chronoamperometry"))
        self.actionSampled_current_voltammetry.setText(_translate("MainWindow", "Sampled current voltammetry"))
        self.actionAbout.setText(_translate("MainWindow", "About Soft Potato"))
        self.actionSave_figures.setText(_translate("MainWindow", "Save figure"))
        self.actionSave_data.setText(_translate("MainWindow", "Save data"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionWiki.setText(_translate("MainWindow", "Wiki"))
        self.actionEFD.setText(_translate("MainWindow", "EFD"))
        self.actionBI.setText(_translate("MainWindow", "BI"))
        self.actionSave_Waveform.setText(_translate("MainWindow", "Waveform"))
        self.actionSave_Current.setText(_translate("MainWindow", "Current"))
        self.actionSave_O.setText(_translate("MainWindow", "[O]"))
        self.actionSave_R.setText(_translate("MainWindow", "[R]"))
        self.actionSave_x.setText(_translate("MainWindow", "x"))
